DROP TRIGGER IF EXISTS addFriend;

CREATE TRIGGER addFriend
AFTER INSERT ON Amizade
BEGIN
INSERT INTO Amizade VALUES (New.ID2, New.ID1);
END;

DROP TRIGGER IF EXISTS removeFriend;

CREATE TRIGGER removeFriend
AFTER DELETE ON Amizade
BEGIN
DELETE FROM Amizade WHERE ID1 = Old.ID2 AND ID2 = Old.ID1;
END;

DROP TRIGGER IF EXISTS updateFriend;

CREATE TRIGGER updateFriend
BEFORE UPDATE ON Amizade
BEGIN
SELECT RAISE(ABORT, 'Cannot update!');
END;